### ISSUE TITLE
Documente as constantes do codigo em java

### ISSUE THREAD

**Issue by kyriosdata** [halkliff/cs-2019-01#36]

**Comment by halkliff** [comment]
As constantes são autoexplicativas. Estarei adicionando uma documentação mínima.

**Comment by kyriosdata** [comment]
A documentação deve ser suficiente e apenas o suficiente, ou seja, mínima,
mas ninguém imagina que nenhuma documentação. Se forem nomes
compreensíveis, então terá pouco trabalho em explicar, mas não podemos
deixar o leitor "imaginar" o que seja.

Fábio
