### ISSUE TITLE
Substituir RangeException por IllegalArgumentException

### ISSUE THREAD

**Issue by kyriosdata** [halkliff/cs-2019-01#4]
RangeException é exceção específica do contexto de manipulação de DOM, não tem ligação com os algoritmos requisitados. Sintaticamente sim, mas semanticamente é um engano.  Caso não queira substituir por IllegalArgumentException, então você deve pensar em criar a sua propria exceção. No contexto desta atividade talvez algo como AlgoritmoException, por exemplo.

**Comment by halkliff** [comment]
A ideia era representar o mais próximo possível uma exceção que demonstrasse o que acontece quando der erro. Mas agora pensando melhor e ainda levando em consideração o cenário proposto, é de se levar em conta que precise ter uma exceção própria.
